# permissions for end users to view authorizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authorization-viewer-role
rules:
- apiGroups:
  - paradox.macro.re
  resources:
  - authorizations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - paradox.macro.re
  resources:
  - authorizations/status
  verbs:
  - get
