# permissions for end users to edit organizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: organization-editor-role
rules:
- apiGroups:
  - paradox.macro.re
  resources:
  - organizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paradox.macro.re
  resources:
  - organizations/status
  verbs:
  - get
